## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly

cache:
  directories:
  - $HOME/.julia/artifacts

env:
  global:
    - DOCUMENTER_DEBUG=true

after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("TickTock")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
