name = "TickTock"
uuid = "ae44564e-183d-4fb0-a137-569fde54f0fc"
authors = ["cormullion <cormullion@mac.com>"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
